version: '3.9'

services:
  frontend:
    image: ghcr.io/theismol/p5-food-recognition/frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://130.225.37.189:2000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - swarm-network

  backend:
    image: ghcr.io/theismol/p5-food-recognition/backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - recipes
      - ingredients
      - image-rec
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - swarm-network

  recipes:
    image: ghcr.io/theismol/p5-food-recognition/recipes:latest
    env_file:
      - ./.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - swarm-network

  ingredients:
    image: ghcr.io/theismol/p5-food-recognition/ingredients:latest
    env_file:
    - ./.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - swarm-network

  image-rec:
    image: ghcr.io/theismol/p5-food-recognition/image-rec:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: overlay

