version: '3.9'

services:
  backend:
    image: ghcr.io/theismol/p5-food-recognition/backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - recipes
      - ingredients
      - image-rec
    networks:
      - app-network

  recipes:
    image: ghcr.io/theismol/p5-food-recognition/recipes:latest
    env_file:
      - ./.env
    networks:
      - app-network

  ingredients:
    image: ghcr.io/theismol/p5-food-recognition/ingredients:latest
    env_file:
      - ./.env
    networks:
      - app-network

  image-rec:
    image: ghcr.io/theismol/p5-food-recognition/image-rec:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

